runtime: python39
instance_class: F2

entrypoint: streamlit run test_app.py --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false --server.enableWebsocketCompression=false

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  PYTHONUNBUFFERED: "true"
  STREAMLIT_SERVER_PORT: "8080"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
  STREAMLIT_CLIENT_TOOLBAR_MODE: "minimal"
  STREAMLIT_THEME_BASE: "light"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1

network:
  forwarded_ports:
    - 8080
  instance_tag: websocket
  session_affinity: true

