runtime: python39
instance_class: F2

env_variables:
  GOOGLE_CLOUD_PROJECT: "smart-video-449213"
  STREAMLIT_SERVER_PORT: "8080"
  BUCKET_NAME: "smart-video-449213-temp"

entrypoint: streamlit run streamlit_app.py

handlers:
- url: /.*
  secure: always
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

network:
  session_affinity: true

