runtime: python39
instance_class: F2

env_variables:
  GOOGLE_CLOUD_PROJECT: "smart-video-449213"

handlers:
- url: /.*
  script: auto

entrypoint: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 5

