runtime: python39
instance_class: F2

entrypoint: streamlit run test_app.py --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false

env_variables:
  PYTHONUNBUFFERED: "true"
  STREAMLIT_SERVER_ENABLE_WEBSOCKET_COMPRESSION: "false"
  STREAMLIT_SERVER_PORT: "8080"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1

