runtime: python39
instance_class: F2

env_variables:
  GOOGLE_CLOUD_PROJECT: "smart-video-449213"
  PORT: "8080"

handlers:
- url: /.*
  script: auto
  secure: always

entrypoint: bash startup.sh

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 5

network:
  session_affinity: true

