runtime: python311
env: flex

entrypoint: streamlit run test_app.py --server.address=0.0.0.0 --server.headless=true

env_variables:
  PYTHONUNBUFFERED: "true"

network:
  session_affinity: true
  forwarded_ports:
    - 8080

handlers:
- url: /.*
  script: auto
  secure: always
  http_headers:
    Upgrade: $HTTP_UPGRADE
    Connection: Upgrade

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

