runtime: python39
instance_class: F2

env_variables:
  GOOGLE_CLOUD_PROJECT: "smart-video-449213"
  PORT: "8080"
  PYTHONUNBUFFERED: "true"
  STREAMLIT_SERVER_PORT: "8080"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_SERVER_BASEURL_PATH: ""
  STREAMLIT_SERVER_ENABLE_CORS: "false"
  STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION: "false"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_RUN_ON_SAVE: "false"

handlers:
- url: /_stcore/stream.*
  script: auto
  secure: always

- url: /_stcore/.*
  script: auto
  secure: always

- url: /stream.*
  script: auto
  secure: always

- url: /.*
  script: auto
  secure: always

entrypoint: streamlit run test_app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.runOnSave=false

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

network:
  session_affinity: true
  forwarded_ports:
    - 8080
  instance_tag: streamlit

liveness_check:
  path: "/_stcore/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/_stcore/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

