name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    # Cache pip packages
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python3.9/site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Cache Google Cloud SDK
    - name: Cache Google Cloud SDK
      uses: actions/cache@v3
      with:
        path: ~/.config/gcloud
        key: ${{ runner.os }}-gcloud-sdk-${{ hashFiles('**/.gcloudignore') }}
        restore-keys: |
          ${{ runner.os }}-gcloud-sdk-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'
        project_id: 'smart-video-449213'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Google Cloud project
      run: |
        gcloud config set project smart-video-449213
        gcloud auth configure-docker

    # Cache App Engine deployments
    - name: Cache App Engine deployments
      uses: actions/cache@v3
      with:
        path: ~/.cache/google-cloud-appengine-python
        key: ${{ runner.os }}-appengine-${{ hashFiles('**/*.py', '**/*.yaml') }}
        restore-keys: |
          ${{ runner.os }}-appengine-

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet
      env:
        GOOGLE_CLOUD_PROJECT: smart-video-449213
