name: Deploy Streamlit App to Google App Engine

on:
  push:
    branches:
      - main  # Deploy on pushes to the main branch
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Authenticate with Google Cloud using service account key
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.6.0  # Use the latest stable version
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'app-engine-python'

    # Step 4: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Deploy to Google App Engine
    - name: Deploy to App Engine
      run: gcloud app deploy --quiet
